In [ ]:
import numpy as np

1

In [ ]:
x = np.ones((10, 10), dtype=int)
x[1:-1, 1:-1] = 0
print(x)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


2

In [ ]:
i, j = np.indices((8,8))
a = (i+j) % 2
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


3

In [ ]:
x = np.arange(25, dtype=int).reshape((5,-1))
x[x % 6 != 5] = -1
x = (x+1)/6
print(x)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


4

In [ ]:
x = np.random.random((5, 5))
m = np.mean(x, axis=1).reshape(-1,1)
x -= m
print(x)

[[ 0.42223597 -0.17854749 -0.38051212 -0.13559141  0.27241505]
 [-0.00693808 -0.36775115 -0.14751119  0.13952945  0.38267098]
 [-0.54110112  0.24006698 -0.30760159  0.26358194  0.34505379]
 [ 0.23569274  0.00507301 -0.46245585  0.19497692  0.02671318]
 [-0.30342878 -0.27718894  0.21334019  0.02247518  0.34480234]]


5

In [ ]:
x = np.random.random((10,3))
print(x)
cl = x[np.arange(len(x)), np.argmin(np.abs(x - 0.5), axis=1)].reshape(-1,1)
print(cl)

[[0.38736178 0.03735    0.56222835]
 [0.73751453 0.49744621 0.05528667]
 [0.51985012 0.22972578 0.43551751]
 [0.33835994 0.35465252 0.64368593]
 [0.44188483 0.34497639 0.61713411]
 [0.5482306  0.46018663 0.54648032]
 [0.55968001 0.3085117  0.23770733]
 [0.30748126 0.82585343 0.08348361]
 [0.73347053 0.92836295 0.82583663]
 [0.23151933 0.79556893 0.47283539]]
[[0.56222835]
 [0.49744621]
 [0.51985012]
 [0.64368593]
 [0.44188483]
 [0.46018663]
 [0.55968001]
 [0.30748126]
 [0.73347053]
 [0.47283539]]


6

In [ ]:
x = np.random.random((6,6))
print(x)
print((np.sum(x,1)/np.max(x,0)))

[[0.95350691 0.31221141 0.01528605 0.55140101 0.33563019 0.53028572]
 [0.91665333 0.70764225 0.0307402  0.18973176 0.54491241 0.7174869 ]
 [0.91515523 0.66174986 0.43633155 0.10239644 0.20744354 0.11727988]
 [0.51499688 0.02595227 0.73719638 0.54573269 0.64726713 0.94373376]
 [0.22683066 0.25552961 0.81297145 0.42090977 0.05418728 0.65739628]
 [0.21486208 0.64301108 0.14450564 0.90986529 0.99807417 0.77914234]]
[2.8298917  4.39087245 3.0017739  3.75317    2.43250965 3.90942951]


7

In [ ]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
ind = np.where(x == 0)[0]+1
np.max(x[ind[ind !=len(x)]])

5

8

In [30]:
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
ui, uc = np.unique(i, return_counts = True)
x[ui] += uc
print(x)

[0 1 2 3 5 8]
[1 1 1 1 3 1]
[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]
