In [2]:
import numpy as np

1

In [71]:
x = np.ones((10, 10), dtype=int)
x[1:-1, 1:-1] = 0
print(x)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


2

In [72]:
i, j = np.indices((8,8))
a = (i+j) % 2
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


3

In [74]:
x = np.arange(25, dtype=int).reshape((5,-1))
x[x % 6 != 5] = -1
x = (x+1)/6
print(x)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


4

In [75]:
x = np.random.random((5, 5))
z = []
for i in x:
  xmean=np.mean(i)
  z = np.append(z, (i-xmean)).reshape((5,-1))
print(z)

[[-0.10700854  0.02714286  0.09909378 -0.08614868  0.06692057]
 [-0.55031158  0.16822221  0.03201043  0.23299437  0.11708457]
 [-0.21345609 -0.42123411  0.06815917  0.26753295  0.29899809]
 [ 0.20904503  0.02820583 -0.56236124  0.37637663 -0.05126624]
 [-0.23321256  0.34501356 -0.01132564 -0.05366205 -0.04681332]]


5

In [57]:
x = np.random.random((10,3))
print(x)
for i in x:
    print(min(i,key=lambda y: abs(y-0.5)))

[[0.90201324 0.45442156 0.23120807]
 [0.66881443 0.14220894 0.55202725]
 [0.83113579 0.43895186 0.83150486]
 [0.51107241 0.9175696  0.96964506]
 [0.47093259 0.4097237  0.10648029]
 [0.65089503 0.29110978 0.77149419]
 [0.43806829 0.98699223 0.38050429]
 [0.42684416 0.16971854 0.67090372]
 [0.93704091 0.13675204 0.41837461]
 [0.40883076 0.57536533 0.11027429]]
0.45442156133389877
0.552027252463098
0.43895186201995795
0.5110724086659696
0.47093258670348326
0.6508950299936707
0.43806828510670437
0.42684416206447084
0.4183746081701144
0.5753653286905162


6

In [66]:
x = np.random.random((6,6))
print(x)
print((np.sum(x,1)/np.max(x,0)))

[[0.95350691 0.31221141 0.01528605 0.55140101 0.33563019 0.53028572]
 [0.91665333 0.70764225 0.0307402  0.18973176 0.54491241 0.7174869 ]
 [0.91515523 0.66174986 0.43633155 0.10239644 0.20744354 0.11727988]
 [0.51499688 0.02595227 0.73719638 0.54573269 0.64726713 0.94373376]
 [0.22683066 0.25552961 0.81297145 0.42090977 0.05418728 0.65739628]
 [0.21486208 0.64301108 0.14450564 0.90986529 0.99807417 0.77914234]]
[2.8298917  4.39087245 3.0017739  3.75317    2.43250965 3.90942951]


7

In [70]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
max((x[i] for i in range(1,len(x)) if x[i-1]==0))

5

8

In [68]:
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
for k in range (len(x)):
    x[k] = x[k] + np.count_nonzero(i == k)
print(x)

array([2., 2., 2., 2., 1., 4., 1., 1., 2., 1.])